name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Ana branch üzerinde çalıştır
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=mevlutkutlu_Ses-Tahmin-Uygulamasi
            -Dsonar.organization=mevlutkutlu
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
